export interface Agencia {
  RFC: string;
  alerta;
  alta_SHCP;
  cajones_de_estacionamiento;
  clasificacion_de_comercio;
  clave_municipal: string;
  distinguir_que_obligacion_tiene;
  domicilio_fiscal;
  empresa_propietaria: number;
  es_persona_fisica: boolean;
  estado_de_negocio;
  estatus_de_verificacion;
  fecha_de_alta_de_padron;
  fecha_de_apertura;
  homonimia_de_registro_de_contribuyente: string;
  horarios: Array<undefined>;
  id: number;
  licencia_ecologica;
  licencia_sanitaria;
  nombre_comercial: '';
  nombre_del_representante_legal;
  numero_de_empleados;
  numero_de_telefono;
  observaciones;
  ocupacion_maxima_de_empleados;
  oficina_recaudadora: number;
  padron: number;
  predio;
  propietario;
  razon_social: string;
  regimen_de_empresa;
  registro_patronal_IMSS: string;
  sector_empresarial;
  sitio_de_internet;
  status: number;
  sucursal;
  superficie_construida_del_terreno;
  superficie_del_terreno;
  tipo_de_contribuyente: number;
  tipo_de_contribuyente2: number;
  tipo_de_establecimiento;
  tipo_de_sociedad: number;
  tipo_empresa;
  zona_de_carga_descarga;
}
