export type RootStackParamList = {
  loading: undefined;
  menu: undefined;
  login: undefined;
  caja: undefined;
  profile: undefined;
  cargosPadrones: undefined;
  detallesPadron: undefined;
  'detalle-de-corte': undefined;
  'abrir-corte': undefined;
  'busqueda-padron': undefined;
  'busqueda-avanzada-ciudadano': undefined;
  'busqueda-avanzada-empresa': undefined;
  'busqueda-avanzada-predio': undefined;
  'busqueda-avanzada-vehiculo': undefined;
  'tabla-seleccion': undefined;
  'detalles-seleccion': undefined;
  'recibos-de-caja': undefined;
  'preview-pdf': undefined;
  'listado-padrones': undefined;
  'agencias-search': undefined;
};
